version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=devcamper
    ports:
      - "27018:27017"